# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [7]:
import numpy as np

#### Create an array of 10 zeros 

In [10]:
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [13]:
array = np.ones(10)
array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [16]:
array = np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [19]:
array = np.arange(10,51)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [22]:
array = np.arange(10,51,2)
array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [25]:
array = np.arange(0, 9).reshape(3, 3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [28]:
array = np.identity(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [31]:
array = np.random.normal(0, 1)
array

-0.4333678343997992

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [34]:
array = np.random.normal(0,1,25)
array

array([ 1.32591716,  0.03064806, -0.94648337,  0.47503363,  1.31256007,
       -0.95031426, -0.18028813,  0.433263  ,  1.70968814,  1.9891076 ,
       -0.65680989, -0.85633473, -0.05306391,  0.86568406, -0.16902267,
       -0.18048282,  1.04342015,  0.51784286, -1.3235882 ,  1.49929788,
        0.66974534,  0.96074323,  0.96176069,  0.27403799, -0.95111028])

#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [42]:
array = np.linspace(0, 1, num=20)
array

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [65]:
array = np.arange(1,26).reshape(5,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [81]:
np.sum(array)

<function sum at 0x000001BE40963D70>

#### Get the standard deviation of the values in mat

#### Get the sum of all the columns in mat

In [79]:
np.sum(array, axis=0)

<function sum at 0x000001BE40963D70>

# Great Job!